### ISSUE TITLE
AssertionError in metrics.py when searching

### ISSUE THREAD

**Issue by chanicpanic** [grascii/grascii#16]
The following search causes an `AssertionError`.

`$ grascii search -g n-dv`

Output:

```
(Token('DV', 'DV'), set())
Traceback (most recent call last):
  File "bin/grascii", line 8, in <module>
    sys.exit(main())
  File "lib/python3.9/site-packages/grascii/__main__.py", line 37, in main
    args.func(args)
  File "lib/python3.9/site-packages/grascii/search.py", line 105, in cli_search
    results = search(**{k: v for k, v in vars(args).items() if v is not None})
  File "lib/python3.9/site-packages/grascii/search.py", line 97, in search
    return searcher.search(**kwargs)
  File "lib/python3.9/site-packages/grascii/searchers.py", line 154, in search
    return list(results)
  File "lib/python3.9/site-packages/grascii/searchers.py", line 54, in perform_search
    diff = min(diff, metric(interp, match))
  File "lib/python3.9/site-packages/grascii/metrics.py", line 204, in standard
    return match_distance(g1, g2)
  File "lib/python3.9/site-packages/grascii/metrics.py", line 180, in match_distance
    v1[0] = v0[0] + compute_ins_del_cost(g1[i])
  File "lib/python3.9/site-packages/grascii/metrics.py", line 118, in compute_ins_del_cost
    assert cost > 0
AssertionError
```

**Comment by chanicpanic** [comment]
Oops, looks like `grammar.STROKES` is also missing `TV`.

```
grascii search -g df
```

```
  File "grascii/grascii/metrics.py", line 86, in compute_ins_del_cost
    assert cost > 0, stroke
AssertionError: AnnotatedStroke(stroke='TV', annotations=set())
```
