### ISSUE TITLE
FileNotFoundError when building dictionary with spell check

### ISSUE THREAD

**Issue by chanicpanic** [grascii/grascii#19]
When running `grascii dictionary build` with the `--spell` option, a `FileNotFoundError` occurs because `words.txt` does not exist.

Output:

```
Traceback (most recent call last):
  File "bin/grascii", line 8, in <module>
    sys.exit(main())
  File "lib/python3.9/site-packages/grascii/__main__.py", line 37, in main
    args.func(args)
  File "lib/python3.9/site-packages/grascii/dictionary/build.py", line 334, in cli_build
    build(**{k: v for k, v in vars(args).items() if v is not None})
  File "lib/python3.9/site-packages/grascii/dictionary/build.py", line 326, in build
    builder.build()
  File "lib/python3.9/site-packages/grascii/dictionary/build.py", line 282, in build
    self.load_word_set()
  File "lib/python3.9/site-packages/grascii/dictionary/build.py", line 170, in load_word_set
    with get_words_file("words.txt") as words:
  File "lib/python3.9/site-packages/grascii/utils.py", line 22, in get_words_file
    return io.TextIOWrapper(resource_stream("grascii.words", name),
  File "lib/python3.9/site-packages/pkg_resources/__init__.py", line 1136, in resource_stream
    return get_provider(package_or_requirement).get_resource_stream(
  File "lib/python3.9/site-packages/pkg_resources/__init__.py", line 1608, in get_resource_stream
    return open(self._fn(self.module_path, resource_name), 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'lib/python3.9/site-packages/grascii/words/words.txt'
```

**Comment by chanicpanic** [comment]
Instead of bundling a large words file with the package, perhaps we should allow the user to provide a path to a local words file.
