### ISSUE TITLE
Dynamic Earley doesn't support weights on terminals

### ISSUE THREAD

**Issue by exupero** [grascii/grascii#67]
I've cloned the repo, run `git submodule init` and `git submodule update`, followed by `pip install .`, but after that when I run the example `grascii search -g AB` I get the following error about how "Dynamic Earley doesn't support weights on terminals":
```
Traceback (most recent call last):
  File "/opt/homebrew/bin/grascii", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.10/site-packages/grascii/__main__.py", line 54, in main
    args.func(args)
  File "/opt/homebrew/lib/python3.10/site-packages/grascii/search.py", line 151, in cli_search
    results = search(**{k: v for k, v in vars(args).items() if v is not None})
  File "/opt/homebrew/lib/python3.10/site-packages/grascii/search.py", line 129, in search
    searcher = GrasciiSearcher(**kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/grascii/searchers.py", line 131, in __init__
    self._parser = GrasciiParser()
  File "/opt/homebrew/lib/python3.10/site-packages/grascii/parser.py", line 132, in __init__
    self._parser: Lark = Lark.open(grammar, parser="earley", ambiguity="explicit")
  File "/opt/homebrew/lib/python3.10/site-packages/lark/lark.py", line 504, in open
    return cls(f, **options)
  File "/opt/homebrew/lib/python3.10/site-packages/lark/lark.py", line 380, in __init__
    self.parser = self._build_parser()
  File "/opt/homebrew/lib/python3.10/site-packages/lark/lark.py", line 422, in _build_parser
    return parser_class(self.lexer_conf, parser_conf, options=self.options)
  File "/opt/homebrew/lib/python3.10/site-packages/lark/parser_frontends.py", line 40, in __call__
    return ParsingFrontend(lexer_conf, parser_conf, options)
  File "/opt/homebrew/lib/python3.10/site-packages/lark/parser_frontends.py", line 68, in __init__
    self.parser = create_parser(lexer_conf, parser_conf, options)
  File "/opt/homebrew/lib/python3.10/site-packages/lark/parser_frontends.py", line 215, in create_earley_parser
    return f(lexer_conf, parser_conf, options, resolve_ambiguity=resolve_ambiguity, debug=debug, tree_class=tree_class, **extra)
  File "/opt/homebrew/lib/python3.10/site-packages/lark/parser_frontends.py", line 192, in create_earley_parser__dynamic
    earley_matcher = EarleyRegexpMatcher(lexer_conf)
  File "/opt/homebrew/lib/python3.10/site-packages/lark/parser_frontends.py", line 173, in __init__
    raise GrammarError("Dynamic Earley doesn't support weights on terminals", t, t.priority)
lark.exceptions.GrammarError: ("Dynamic Earley doesn't support weights on terminals", TerminalDef('N', 'N'), 2)
```

**Comment by chanicpanic** [comment]
Based on the error, you may have an old version of `lark`. Could you check your `lark` version?
(The latest version of `grascii` requires `lark>=1.0.0`.)

Alternatively, the issue could be caused by having the old `lark-parser` package in your environment.

**Comment by exupero** [comment]
`pip show lark` reports I have version 1.1.7. `pip show lark-parser` shows 0.12.0, which appears to be the latest version.

**Comment by chanicpanic** [comment]
Most likely the lark from `lark-parser` is getting imported which has an incompatible lark version.

If you have no packages that depend on `lark-parser`, you could uninstall it. Otherwise, you could try installing `grascii` in a new virtual environment.

**Comment by exupero** [comment]
Thanks, uninstalling `lark-parser` worked.
